### ISSUE TITLE
跑不起来，报错

### ISSUE THREAD

**Issue by i-am-zhengyufang** [code-mcx/react-bilibili#22]
报错1：Interface 'NodeRequire' cannot simultaneously extend types 'RequireFunction' and 'Require'. Named property 'resolve' of types 'RequireFunction' and 'Require' are not identical
报错2：Subsequent variable declarations must have the same type.  Variable 'URL' must be of type '{ new (url: string, base?: string | URL): URL; prototype: URL; createObjectURL(object: any): string; revokeObjectURL(url: string): void; }', but here has type '{} | typeof URL'.
还有很多报错，暂时列出了这几个，网上找了很久也没找到答案

**Comment by dxx** [comment]
有可能是 `npm install` 后依赖包的版本问题，对比看下 `package-lock.json` 中对应的版本。

**Comment by i-am-zhengyufang** [comment]
非常感谢，我是组织部干事郑雨芳。您的消息我已收到，我会尽快回复。

**Comment by mc1128-png** [comment]
> 报错1：Interface 'NodeRequire' cannot simultaneously extend types 'RequireFunction' and 'Require'. Named property 'resolve' of types 'RequireFunction' and 'Require' are not identical 报错2：Subsequent variable declarations must have the same type. Variable 'URL' must be of type '{ new (url: string, base?: string | URL): URL; prototype: URL; createObjectURL(object: any): string; revokeObjectURL(url: string): void; }', but here has type '{} | typeof URL'. 还有很多报错，暂时列出了这几个，网上找了很久也没找到答案

请问您解决了吗？

**Comment by mc1128-png** [comment]
> 有可能是 `npm install` 后依赖包的版本问题，对比看下 `package-lock.json` 中对应的版本。

能具体说一下吗，和启动过程
![image](https://user-images.githubusercontent.com/74965562/190994325-286f05f2-3808-4c88-8bb1-b197fc5ceb06.png)

**Comment by dxx** [comment]
React typescript 包相关的版本，你安装的可能不是 package.json 里面的版本，不兼容就报错了

**Comment by rxl123** [comment]
跑起来了，但是页面显示服务器 出错 @dxx

**Comment by dxx** [comment]
@rxl123 服务端api运行起来了吗

**Comment by zhuimingdongma** [comment]
> @rxl123 服务端api运行起来了吗

服务端api咋运行。哥

**Comment by zhuimingdongma** [comment]
> @rxl123 服务端api运行起来了吗

跑起来了,牛逼啊 哥
