### ISSUE TITLE
请问，run dev之后我访问localhost:3010响应服务器失败。

### ISSUE THREAD

**Issue by Rororororororororororororororororororo** [code-mcx/react-bilibili#3]
这个项目该如何正常启动呢

**Comment by Rororororororororororororororororororo** [comment]
自己琢磨了下，启动成功了。发现作者前端功底蛮强的。 能否交流一下吗

**Comment by code-mcx** [comment]
过奖了哈

**Comment by liujett** [comment]
@Rororororororororororororororororororo 咋启动的？大佬

**Comment by usercao** [comment]
@Rororororororororororororororororororo 请问如何解决的？

**Comment by code-mcx** [comment]
@usercao `npm run dev`用的是`config/dev.env.js`中的配置，里面配置的是本地接口地址，本地运行记得把这个地址换成线上的，在`config/prod.env.js`中
