### ISSUE TITLE
请求一下后端开发的相关流程

### ISSUE THREAD

**Issue by qw1004901361** [code-mcx/react-bilibili#6]
大佬 想请问一下你的数据获取的接口大致有什么 我们这个学期大作业想模仿B站做个网页，不需要做完（也做不完~~~） 想问一下访问例如首页时 需要什么接口等等

**Comment by code-mcx** [comment]
打开B站页面，浏览器查看network，看接口请求返回的数据和页面的内容是否能对上，能的对上的就是页面需要的接口。如果没有找到相关接口那就是服务端渲染，数据会存在页面的`script`中，这个时候需要抓页面解析出`script`里面的数据

**Comment by qw1004901361** [comment]
好的 麻烦了
